name = "hypixelapi"
main = "index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sb-vault"
database_id = "e3adacfc-bc07-41cc-9496-4fa17108e846"

[[kv_namespaces]]
binding = "SESSIONS"
id = "39b5f3269c454e768759a0491a85719e"

[vars]
MCID_REDIRECT_URI = "https://seyvault.github.io/"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "sb-vault-images"

[triggers]
crons = ["* * * * *"]

[observability]
enabled = true
head_sampling_rate = 1